FROM liquibase/liquibase:3.10.3

USER root
ENV PATH=/liquibase/:$PATH

RUN wget -O /liquibase/lib/liquibase-percona-1.6.0.jar https://liquibase.jira.com/wiki/download/attachments/47284233/liquibase-percona-1.6.0.jar?api=v2
RUN chown 101:101 /liquibase/lib/liquibase-percona-1.6.0.jar

RUN apt update && apt-get install perl libdbi-perl libdbd-mysql-perl libterm-readkey-perl libio-socket-ssl-perl -y

RUN wget https://www.percona.com/downloads/percona-toolkit/3.1.0/binary/debian/stretch/x86_64/percona-toolkit_3.1.0-2.stretch_amd64.deb && \
    dpkg -i percona-toolkit_3.1.0-2.stretch_amd64.deb

COPY mysql-connector-java-5.1.47.jar /lib/mysql-connector-java-5.1.47.jar

COPY liquibase /liquibase/liquibase
RUN chown 101:101 /liquibase/liquibase

# USER liquibase
ENTRYPOINT ["/bin/bash"]
